SELECT TOP (1000) [ReciclajeId]
      ,[UsuarioId]
      ,[PuntoId]
      ,[FechaRegistro]
      ,[CantidadBotellas]
      ,[PesoKg]
      ,[TipoMaterial]
      ,[EsValido]
  FROM [EcoWrappedDB].[dbo].[Reciclaje]
